### PR TITLE
Add requirement files

### PR DESCRIPTION
**Pull request by crydotsnake**

### CODE REVIEW

**Comment by crydotsnake** [comment]
Wait.. i think i have to move the requirements folder too `tests/requirements` and then, delete the `requirements.txt` in `tests`

**Comment by crydotsnake** [comment]
Is that correct? @marksweb

**Comment by marksweb** [comment]
> Is that correct? @marksweb 

Not quite. Create a requirements directory. Move `requirements.txt` into it and rename it `base.txt`

Then add the other files.

**Comment by crydotsnake** [comment]
@marksweb Now it looks better.. but the Lint check has failed..

**Comment by marksweb** [comment]
> @marksweb Now it looks better.. but the Lint check has failed..

Yeah just import order. Easy fix.

Details here https://github.com/django-cms/djangocms-video/runs/2368886690

**Comment by crydotsnake** [comment]
You mean it should look like that?

```
isort
django-app-helper
tox
coverage
flake8
```

**Comment by crydotsnake** [comment]
Idk how too fix it 😓

**Comment by marksweb** [comment]
> You mean it should look like that?
> 
> ```
> isort
> django-app-helper
> tox
> coverage
> flake8
> ```

Yeah that would be the base requirements which are needed by each Django version we test against.

So that would be included at the top of each of the other requirement files.

**Comment by crydotsnake** [comment]
@marksweb The check has failed again. Have I forgotten a requirements file?

**Review by vinitkumar — APPROVED** [review]

**Review by marksweb — APPROVED** [review]

**Pull request merged**
