### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by crydotsnake**

### CODE REVIEW

**Review by marksweb — APPROVED** [review]

**Comment by marksweb** [comment]
@crydotsnake the requirements files were missing here.

I've jumped the gun on this. Can you please raise another PR with the requirements. The actions should run successfully on your branch before you need to raise the PR

**Comment by crydotsnake** [comment]
@marksweb which requierements you mean?. `tests/requirements.txt` ?

**Comment by marksweb** [comment]
> @marksweb which requierements you mean?. `tests/requirements.txt` ?

No, that's what it used to use. These actions require a change to the requirements setup.

Take a look at one of the repos that I've already made this change on, or read through the test action. It shows the requirements files it needs and the path it expects to load them from.

**Comment by crydotsnake** [comment]
You mean those files?: https://github.com/django-cms/djangocms-snippet/tree/master/tests/requirements

**Comment by marksweb** [comment]
> You mean those files?: https://github.com/django-cms/djangocms-snippet/tree/master/tests/requirements

That's right. The old `requirements.txt` becomes the base which the others all import & define the other versions according to the file name.

That's then referenced in the test action

**Pull request merged**
